name: Trigger auto deployment for cntxcontainerapps-api-01ee114b

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cntxcontainerapps-api-01ee114b-AutoDeployTrigger-26a7ed65-8e85-413e-aa00-6f6cfd418c67.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CNTXCONTAINERAPPSAPI01EE114B_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CNTXCONTAINERAPPSAPI01EE114B_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CNTXCONTAINERAPPSAPI01EE114B_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: cntxacr.azurecr.io
          registryUsername: ${{ secrets.CNTXCONTAINERAPPSAPI01EE114B_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CNTXCONTAINERAPPSAPI01EE114B_REGISTRY_PASSWORD }}
          containerAppName: cntxcontainerapps-api-01ee114b
          resourceGroup: cntxcontainerapps-rg-01ee114b
          imageToBuild: cntxacr.azurecr.io/cntxcontainerapps-api-01ee114b:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


